name: .NET CI

on:
  push:
  pull_request:
    branches: [ main ]

permissions:
  contents: write   # Required so the workflow can push tags

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --no-restore --configuration Release

      # Optional tests
      # - name: Run tests
      #   run: dotnet test MobyParkAPI.Tests/MobyParkAPI.Tests.csproj --no-build --configuration Release --logger trx

      - name: Generate new Git tag - step 1
        id: tag
        run: |
          git fetch --tags
          git tag -l
          git ls-remote --tags origin


      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: MobyParkAPI-${{ env.NEW_TAG }}
          path: ./bin/Release/**/*
          if-no-files-found: error
